### ISSUE TITLE
Consider using npm `dist-tag` to tag prerelease versions

### ISSUE THREAD

**Issue by fiznool** [NodeRedis/node_redis#1026]
npm has a concept of [dist tags](https://docs.npmjs.com/cli/dist-tag) to allow releases to be marked as stable, and unstable. npm itself is released using the following process:

- Stable release: tagged with `latest`. This is what gets installed when you type `npm install <package>`.
- Prelease: tagged otherwise, their convention is `next`. This can be installed with `npm install <package>@<tag>`.

This will help, as it means that regular users of the module will receive the latest stable version (2.5.3 at time of writing) when using `npm install`, whereas users that need the newer features can install the prelease (2.6.0-0 at time of writing) if they need to. It also means that `package.json` entries such as `^2.5.3` won't get updated to the prerelease when running `npm update`.

**Comment by BridgeAR** [comment]
@fiznool thanks for pointing this out.

node_redis uses the [semver](https://docs.npmjs.com/misc/semver) versioning and if I'm not wrong it should behave just the same for the pre-release versions by using the pre-release syntax instead of a dist-tag.

Running `npm update` with entries like `^2.5.3` won't be updated therefore.

Running `npm install` without a package json entry is going to return the latest version, therefore the pre-release. If you have a entry in your package json, it'll check what range is allowed.

So I guess that's fine as it is?

I consider the pre-releases stable, but I want to make sure that they are tested by others. I tried to implement smoke tests by checking other libraries test suites but I did not find thoroughly tested ones (if anyone can point me out to one / some, that would be awesome!).
Mostly it's because the change is not a trivial change and you might have a oversight and besides that I don't test really old Redis versions either.

**Comment by fiznool** [comment]
Sorry for the late reply.

I guess my point was really surrounding `npm install redis`. I would expect this to pull down the latest stable version, not a prerelease. To me, 'prerelease' is synonymous with 'unstable', but maybe that's just me!

**Comment by fiznool** [comment]
My other use case is checking for updates with `npm outdated` or `npm-check-updates`. These will return the prerelease as the 'latest', when in reality, I'd rather stick with the latest stable.

**Comment by BridgeAR** [comment]
@fiznool the reason for a pre-release in my opinion is about letting some people test your release. The release is hopefully in a state that it's possible to use it (and it should in my opinion, otherwise at least I would not release anything) and it's about finding edge cases that might be resolved before hitting someone in production.

And I can't think of anyone building a Node.js app for production without using a package json with appropriate version ranges. Besides the fact that v.2.6.0-1 is almost under certainty the most stable node_redis version ever (In fact there are no known bugs left besides #932 that might count as such but it's difficult to find a good solution for that one). But there might be a case that worked a tiny bit different for someone earlier that I did not think about and I would like to prevent people from running into issues in production.

But if no one is going to receive that update there's no meaning in publishing it in the first place (yes, that's a bit exaggerated ;) ).

I agree though that it is inconvenience that `npm oudated` lists these releases. I'll have another thought about it as soon as I release another pre-release. Thanks again for bringing it up!

**Comment by metaraine** [comment]
Pre-releases can be published to specific tags other than latest:
npm publish --tag next

The community can vet the code and provide feedback by installing this tag;
npm install redis@next

This allows code to be tested without accidentally releasing a bug on the latest branch that users consider to be stable. 

Sure you can just release to latest and plan on fixing any bugs that users uncover, but if that's the case, why call it a pre-release to begin with? Just release it as x.0.0 and then patch as x.0.1 as necessary. 

I am the maintainer of npm-check-updates and this is the most common behavior I have seen across other node modules fwiw.

**Comment by doliver3** [comment]
Instability is encouraged by making the default behavior of npm publish to always tag prereleases as latest.  Prereleases should not be tagged as latest by default. 

When users install a package without a version number, they want the latest stable release - not unstable prereleases.
