### ISSUE TITLE
Random connection errors

### ISSUE THREAD

**Issue by ryanwe** [NodeRedis/node_redis#1027]
* **Version**: node_redis versions `2.2.5` and `2.6.0-0`. Redis version `2.8.12`
* **Platform**: Node.js `0.12`
* **Description**: 

I recently encountered the same error reported in #1024. Initially we were running node_redis version `2.2.5`. 

We started seeing these occasional errors:

```
error: message="Redis error", error="Error: subscriptions are active but got an invalid reply: OK"
  at RedisClient.return_reply (/app/node_modules/redis/index.js:638:32)
  at /app/node_modules/redis/index.js:309:18
```

After seeing your recent fixes for pubsub, we upgraded node_redis to `2.6.0-0`. The error didn't go away but instead it looked like the one mentioned in #1024:

```
error: message="Redis error", error="Error: Redis connection lost and commands aborted in uncertain state. They might have been processed." 
at RedisClient.connection_gone (/app/node_modules/redis/index.js:576:17) 
at Socket.<anonymous> (/app/node_modules/redis/index.js:245:14) 
at Socket.g (events.js:199:16) 
at Socket.emit (events.js:129:20) 
at _stream_readable.js:908:16
```

According to the stack trace, it appears that the connection is being cut by the db itself but we see nothing to indicate that is the case. It's also unclear what commands "might have been processed" and if we should consider this a warning instead of an error.

Sadly, I don't have a repro for this problem. We see it in our logs every 5 to 30 minutes but don't know the cause. However, I'd be happy to try and validate that a fix causes the errors to stop.

It might be helpful to know what messages aren't being processed since our `get`, `set`, and `publish` calls all use callbacks for error handling and we haven't seen them fail.

And if the failures are in `subscribe` (which doesn't use a `(error, result)` style callback) and node-redis automatically reconnects and re-subscribes, should this be an error?

Any help in understanding the nature of this problem and what's causing these errors is greatly appreciated.

Thanks!

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
@ryanwe the first error indicates an error in node_redis. Do you have some code that triggered this at least partly reproducible? Even though I guess it is already fixed by the recent pub sub fixes as you did not run into it anymore (please run your code with v.2.6.0-1 though, as there were some further fixes concerning reconnecting in pub sub mode). 

The second error really indicates network issues as you already mentioned. With the error you should at least also see the command name of the fired command, if you look at the original error properties. That way it should be easier to see what command might have been processed (and yes, this can and will be improved further at some point by adding the arguments and also a better stack trace out of production mode).
That error returns in every callback, so if your subscribe calls are the only ones without, it is indeed likely that those fail (but it might also be a info command run by node_redis itself after connecting).

Do you maybe use the azure Redis cache? I remember connection losses with that network in another issue. You might want to check further on how the stream works, when it is connected or looses a connection and what errors it receives (by using the `retry_strategy` or listening to the `reconnecting` event you also receive the error that resulted in the network loss).

**Comment by ryanwe** [comment]
Thanks for the quick reply @BridgeAR!

We're running in Heroku against a managed addon (RedisCloud) provided by RedisLabs. I'm working with them to investigate any network issues but they haven't found anything on their end yet.

In the meantime, I'll upgrade us to 2.6.0-1, and add a listener to `reconnecting` to try and get more information about the error. I'll update this issue when I know more.

**Comment by ryanwe** [comment]
RedisLabs moved us to a new node which includes some software updates on their end and the errors have gone away. I'm going to deploy the changes mentioned in my previous comment and will continue to monitor things, but it looks like this was a connection/networking issue with RedisCloud.

Thanks again for your help!

**Comment by BridgeAR** [comment]
This sounds good. As a further hint: If the server side drops the connection and node_redis is able to reconnect properly there is likely not going to be any error / message besides the warning that the connection is lost and node_redis is reconnecting.
