### ISSUE TITLE
RedisClient.address always set to "127.0.0.1:6379" when 'options.tls' is set

### ISSUE THREAD

**Issue by mmoskal** [NodeRedis/node_redis#1035]
The field is set here:
https://github.com/NodeRedis/node_redis/blob/master/index.js#L64

before the 'tls' options are copied. This leads to error message that read:

```
Redis connection to 127.0.0.1:6379 failed - read ECONNRESET
```

instead of say:

```
Redis connection to myserver.net:6380 failed - read ECONNRESET
```

**Comment by mitchjmiller** [comment]
Came across this same issue and it was very misleading and sent me down a massive rabbit hole wondering why my client was trying to connect to localhost. Turns out it wasn't...

My issue is the same as with the OP. The address field is only set based on the passed in host and port, and not the tls ones passed in. Of course if the defaults are left undefined then they default to 127.0.0.1:6379.

Easy fix is to simply add a line in the tls options check to set the address appropriately.
For the moment I've simply added the host and port to the base options, as well as the tls options. Little messy but it works.

**Comment by BridgeAR** [comment]
The reason is that this was not the original intention when implemented. But this is indeed very misleading and a totally valid usage. Originally it was only thought about adding the port / host or the path in the options and all other tls options in the specific tls options.

Please feel free to open a pull request for it. I'm aboard at the moment and have little time, so this would be help to implement it faster.
