### ISSUE TITLE
allow handling of "READONLY You can't write against a read only slave." with retry_strategy

### ISSUE THREAD

**Issue by samzilverberg** [NodeRedis/node_redis#1050]
* **Version**: 2.5.3
* **Platform**: node js 0.10.x 

similiar to #830 but not about supporting multiple connection strings, rather about error handling and retry.

What i've experiences using ElasticCache, is that when the master is demoted, the next 'write' operation (set) would return this error:
READONLY You can't write against a read only slave.

I've tried writing a retry_strategy to catch this kind of error (and also a stale connection one) but it doesnt seem to be catching this one.
I tried some debugging and cant seem to see the retry_strategy catching this kind of err.

am i doing something wrong? or is the lib not using retry_strategy for this kind of err?

**Comment by BridgeAR** [comment]
The returned error is handled in the callback of your fired command. It can never reach the `retry_strategy` as it's only meant to be used for connection issues.

I guess the name is a tiny bit misleading here... I never thought about this interpretation but I totally see it after you mentioning it.

Currently you have to retry that command on your own. This is especially important as the execution order is almost under certainty not the same afterwards. This should be fixed by implementing cluster. Depending on your architecture you could check for the READONLY error code and retry that command afterwards.

**Comment by samzilverberg** [comment]
thanks for the quick response.
will handle this case in the callback as suggested.

> I guess the name is a tiny bit misleading here... I never thought about this interpretation but I totally see it after you mentioning it.

i've reread the documentation for 'retry_strategy' and it actually does say ``` ... the error why the connection was lost ... ``` somewhere in the middle.  
I can only recommend to edit the README and make it a little more obvious that retry_strategy is only meant for conn lost errors

thanks!
