### ISSUE TITLE
Documentation text color

### ISSUE THREAD

**Issue by paulomcnally** [NodeRedis/node_redis#1110]
Documentation text color from http://redis.js.org/ it's very difficult to read.

Alternative color #333

**Comment by paulomcnally** [comment]
Now color #2badad

**Comment by will-ob** [comment]
:+1: :+1: :+1: 
http://leaverou.github.io/contrast-ratio/#%232badad-on-white

**Comment by BridgeAR** [comment]
@paulomcnally would you be so kind and open a pull request for this?

**Comment by paulomcnally** [comment]
@BridgeAR Of course

**Comment by BridgeAR** [comment]
When we spoke about this I forgot where the code resides on our end and therefore did not point you to the right direction.

The code is actually in the `gh-pages` branch. We should change the color there instead of the used library.

Closing this as a duplicate for now - let's continue to talk in #1234.
