### ISSUE TITLE
I want to use it to connect codis,but I fail,how can i use it to connect codis?

### ISSUE THREAD

**Issue by WebCaiQingChong** [NodeRedis/node_redis#1247]
I use express,and express-session,to ensure the session shared,the express-session of store use redis. but in our company,they use codis.

**Comment by jdegger** [comment]
Hi @WebCaiQingChong, you ask your company for the connection details of the Codis Proxy Server which you can use in your configuration instead of the normal Redis connection.

Closing this as this is not really an issue for NodeRedis. You can contact the Codis devs for more information if it's not working.

Good luck!
