### ISSUE TITLE
selected_db is undefined

### ISSUE THREAD

**Issue by zhaoyao91** [NodeRedis/node_redis#1267]
if the redis url provided to create the redis client does not contains the `db` part, say, `redis://localhost` instead of `redis://localhost/0`, then the redis will connect to db 0 but the client.selected_db and client.options.db is undefined.

**Comment by BridgeAR** [comment]
`selected_db` is a internal value that should not be used and the options is something the user provides to the client.
The behavior itself is correct though as the client will not fire a `select` query to Redis.
As the default for new clients is always to connect to db 0 it would be fine though to set `selected_db` to 0 as a default and check for "!== 0" while reconnecting instead of "!== undefined".

@zhaoyao91 I would be open for a PR

**Comment by zhaoyao91** [comment]
if selected_db is not intended to be used by user, then how could I get the current connected db of this client? You know when subscribe the keyspace notifications the db index is an important part.

**Comment by BridgeAR** [comment]
This information is part of the `server_info` property that is set as soon as the client is connected.

And as @jdegger said: it's safe to assume that the client connects to `db0` by default.
