### ISSUE TITLE
Pipelining example in documentation

### ISSUE THREAD

**Issue by cn007b** [NodeRedis/node_redis#1288]
On [npm page](https://www.npmjs.com/package/redis) in keywords present `pipelining` but in examples - nothing... Could you please provide super simple pipelining example in the documentation.

Thank you in advance!

**Comment by stockholmux** [comment]
See [batch](https://github.com/NodeRedis/node_redis#clientbatchcommands). It's covered in that section (works just like a `multi`/`exec` but instead of `multi` you call `batch`).

There are some historical reasons and technical reasons why it's not called 'pipeline' - in some circumstances it just pipelines by default - the client doesn't stop for responses to go on to send the next command. However, when you want more precise control over the pipeline, `batch` is what you want.
