### ISSUE TITLE
Ready check failed: Redis connection lost and command aborted

### ISSUE THREAD

**Issue by junaidahmed93** [NodeRedis/node_redis#1292]
Hello everyone,

I am trying to connect node_redis in a sample. connection immediately lost after connect. Could anyone please help.

npm:  3.10.10
node: 6.11.4
redis: 2.8.0

Here is my code: 

```
var express = require('express');
var bodyParser = require('body-parser');
var path = require('path');
var redis = require("redis"),
client = redis.createClient("5000");

var app = express();
app.set("port", 5000);

var staticDIR = path.resolve(__dirname, "./public/src");
app.use(express.static(staticDIR));
app.use(bodyParser.json());


app.listen(app.get("port"),()=>{
    console.log("Server started");
})
```

Here is error:

```
Server started

events.js:160
      throw er; // Unhandled 'error' event
      ^
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (C:\Users\Junaid\Desktop\Sample-Redis\node_modules\redis\index.js:362:23)
    at RedisClient.connection_gone (C:\Users\Junaid\Desktop\Sample-Redis\node_modules\redis\index.js:664:14)
    at Socket.<anonymous> (C:\Users\Junaid\Desktop\Sample-Redis\node_modules\redis\index.js:293:14)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by koreanilkumar** [comment]
I'm getting the same error. I'm using the redis version is 2.8.0. Any fix for this. I'm making ssl connection with redis with NodeJS

**Comment by stockholmux** [comment]
@junaidahmed93  and @koreanilkumar These are the result of a broken connection- e.g. you somehow lost connection with the Redis server. In the code, we're dealing with one of two scenarios (or both) - the connection has timed out or the the reconnect attempts have exceeded the maximum number specified in a config. I would double check your connection information and how your redis server is configured.

@junaidahmed93 - I'm seeing a few specific problems:
`redis.createClient("5000")` - this indicates 5000 as your Redis port number. It shouldn't be in quotes - as a port number should be a simple number value, not a number inside a string. Later, you're setting Express to host on 5000 too - that won't work. Likely setting your port number correctly (better yet, specify a object with host, port, etc.) will solve your problem. But it's all configuration issues.

I'm going to close this since it's coming from configuration problems or outside the scope of the module
