### ISSUE TITLE
No any callback or reconnection after network disconnected

### ISSUE THREAD

**Issue by JoHuang** [NodeRedis/node_redis#1299]
* **Version**: v2.8.0
* **Platform**: Node.js v8.9.3 on Ubuntu 16.04.3 LTS
* **Description**: no any callback or reconnection after network disconnected

1. connect to Redislab, on('ready') called
2. turn off the internet network, no any callback or reconnection forever.

PS. if the network is disconnected in the first place, I can see reconnecting callback.

**Comment by BridgeAR** [comment]
The reason is that there is no proper keep alive mechanism and it is not really possible to add that. So for the keep alive the system default timeout is used and that is normally about 2 hours. A similar issue: #941.

There is sadly not much that can be done about this at the moment :disappointed:. Therefore I am closing this.

**Comment by JoHuang** [comment]
So what should I do if that happened? How to recover the system?

**Comment by BridgeAR** [comment]
One of the best ways right now is probably to have a constant ping every x seconds / minutes. As soon as the ping needs longer than x to come back try to reconnect.
