### ISSUE TITLE
How to handle idle clients left when objects get garbage collected

### ISSUE THREAD

**Issue by quentin-sommer** [NodeRedis/node_redis#1338]
* **Version**: NA
* **Platform**: NA
* **Description**:

Hi, I'm using redis as a cache for an object that is created and deleted many times during the runtime of a server. When my object gets garbage collected the redis client stays connected to the server, creating an infinite increase in connected clients.

Do you know if there's any other solutions than adding a timeout to redis or adding a "destructor" method to my object? I've got several others programs using redis and can't be sure it won't break a ton of stuff

**Comment by stockholmux** [comment]
It's a bit hard to understand what you're doing without code, but create a single top level client and just request off of that. Node is single threaded - there is very little advantage to creating multiple clients under most circumstances.

I'm going to close since this isn't really an issue with the module.
