### ISSUE TITLE
Callback for client.get is not fired when client.auth is done in its own callback

### ISSUE THREAD

**Issue by datdinhquoc** [NodeRedis/node_redis#1372]
* **Version**: node_redis 2.6.5, redis server 3.2.13
* **Platform**: node 10.9.0, centos 7 x64
* **Description**: Callback for client.get is not fired when client.auth is done in its own callback

### Reproducing steps:
1. Try to authenticate in the callback of previous failed auth (I faced this case because we have 2 possible passwords, same code + different servers with different redis configs):
```javascript
client.auth("some-wrong-password",function(err,result){
    if (err==null)
        return;

    client.auth("correct-password-here",function(err,result){
        console.log("Connected");
    });
});
```

2. After getting connected, try client.get
```javascript
client.get("whatever-key",function(err,result){
    console.log("This callback function is never fired!");
});
```

### Current result
The callback function inside client.get is never called.

### Expected result
The callback function inside client.get must be called.

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by stockholmux** [comment]
OK - `client.auth` works differently that what you think. It is special for [reconnection reasons](https://github.com/NodeRedis/node_redis#clientauthpassword-callback). What you are seeing is expected behaviour really.

Effectively, you _can't_ call `AUTH` twice from a node_redis script on the same client, so you have to make a new client if your connection fails, so you have to make a new client object if the first one fails.

This accomplishes what you're trying to do I think.

```
const
        redis   = require('redis'),
        clientConfig    = { no_ready_check : true };
let
        client  = redis.createClient(clientConfig);

function doStuff() {
        client.get('hi',function(err,result) {
                if (err) throw err;
                console.log('hi=',result);
        });
}

client.auth('mywrongpassword',function(err) {
        if (err) {
                client.quit();
                client = redis.createClient(clientConfig);
                client.auth('mycorrectpassword',function(err) {
                        if (err) throw err;
                        doStuff();
                });
        } else {
                doStuff();
        }
});
```

Also, I couldn't quite understand from your example how you are managing async so I filled in the gaps with `doStuff`.

**Comment by datdinhquoc** [comment]
client.auth should be called once per client instance, i see, thanks for clarifying,
