### ISSUE TITLE
Not clear how to subscribe to streams

### ISSUE THREAD

**Issue by Ventis** [NodeRedis/node_redis#1394]
Hi,

since Redis version 5.0, streams have been introduced as a new data type.
Since the update of redis-commands, new commands like `xread` and `xadd` have been added. However, it's not clear to me how one implements a permanent subscription to a stream without having to call `xread` over and over again. I thought I found the answer in the `BLOCK` parameter but I doesn't seem to work as I expected:

```
client.xread('BLOCK', 1000, 'STREAMS', 'myStream', '$', (err, stream) => {
      if (err) return console.error('Error reading from stream:', err);
      console.log('Stream:', stream);
      // How many times is this called?
    });
```

My question is, how can you make the callback passed to the xread command a permanent one that gets called every time a new message is added to the stream? (like the on 'message' callback in subscribe).

It can't be that you need to put this between a `while(true)` loop to continuously poll the stream, right?

* **Version**: node_redis: ^2.8.0 , Redis: 5.0.1-alpine docker image
* **Platform**: Node.js 0.10 on Ubuntu
* **Description**: Can't 'listen' to a Redis Stream like you can to channel?

**Comment by gkorland** [comment]
You don't need do a while() but to recall xread() in the callback function using the Stream ID you are getting.
Each xread call is a single blocking call as opposed to pub-sub subscribe.  
Only the first call should be using $ and that only if you want to avoid getting the history.

See: https://redis.io/commands/xread#the-special-codecode-id

**Comment by Ventis** [comment]
The Redis documentation is very unclear about explaining the streams concept, because in the _Introduction to Redis Streams_ they speak of streams like it's similar to PubSub. Regardless, if you want to create a node backend that continuously listens for new data on a stream it seems very inefficient to recursively call xread with the last id received (especially since you also need to store the last read id).

Does that also mean that clients that want to read from a stream are also responsible to keep the last read id in memory?

**Comment by stockholmux** [comment]
@Ventis From the perspective of calling the `XREAD` command it's nearly identical to blocking list commands (`BLPOP`, for example). 

I've used the (`async.forever`)[https://caolan.github.io/async/docs.html#forever] (from the `async` module) command successfully for continuously listening commands. Store the last ID in a higher scope then it becomes quite simple. 

You can persist the last read ID in whatever way you want - as variable or with something more persistent - that's up to you. You should also check out the consumer group API for streams - that might enlighten some of your questions as far as managing reads. You can read from multiple streams - but be careful of this in cluster.

 Since `XREAD` command is executing and this module doesn't document individual commands (that's the job of redis.io), I'm going to go ahead and close this issue.
