### ISSUE TITLE
How to query with multiple commands

### ISSUE THREAD

**Issue by pawarvijay** [NodeRedis/node_redis#1423]
* **Node Redis Version**: ^2.8.0
* **Redis Version**: 5.0.3
* **Platform**: Node.js 10.13.0 ubuntu
* **Description**: How to implement below query with multiple commands

red ferrari with limited edition
with topSpeed between 200 To 210 And
Price between 190 to 205

```
HMSET cars:1 make ferrari Price 199 limited yes color red topSpeed 202
HMSET cars:2 make porsche Price 555 limited no color yellow topSpeed 500

SADD make:ferrari 1
SADD color:red 1
SADD limited:yes 1
ZADD Price 199 1
ZADD topSpeed 202 1

SADD make:porsche 2
SADD color:yellow 2
SADD limited:no 2
ZADD Price 555 2
ZADD topSpeed 500 2
```
**what i tried**

```
multi.ZINTERSTORE('tempTom',4,
'color:red',
'make:ferrari',
'limited:yes',
'topSpeed'
);

multi.ZRANGEBYSCORE('tempTom' , 200 ,210) //range for topSpeed

//so how to add range for Price also ?
```
**Output** 

```
[1,[]]
```
please guide me what wrong i am doing.
also there are very less articles on complex queries in redis 

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
I am very sorry but I can sadly not provide any support how to use Redis itself. Since this is not node_redis related, I'll close this. Sadly my time is very limited and I must limit that time to the issues related to node_redis itself. You may contact me in private in case you would like to hire me as consultant.
