### ISSUE TITLE
Please help! Redis commands run slower and slower

### ISSUE THREAD

**Issue by indieyourself** [NodeRedis/node_redis#1457]
let beginTime = Date.now();

      client.send_command(cmd, args, function (err, res) {
          let elapsed = Date.now() - beginTime;
          if (elapsed > 10) {
              console.log('redis cmd elapsed more than 10!! elapsed:%s cmd:%s ', elapsed, cmd);
          }
          if (err) {
              reject(err);
          } else {
              resolve(res);
          }
      });`

I have a million keys in Redis. I just run MGET/GET one key each time, using above code . After a while , the elapsed become larger and larger. Why?

**Comment by stockholmux** [comment]
First, you should confirm that you are measuring what you're intending to measure. `beginTime`, I assume, is being reset every time (can't tell from your snippet exactly).

Second, `MGET` and `GET` are very different in some situations. Just use one to compare apples to apples.

Third, if you are running this in some sort of loop asynchronously a million times, you're likely over-pipelining the server. Redis will continually accept commands and serve those commands back in order. The first command is under 0 load and is very quick. The 100,000th command is most likely under a very different load as a backlog of commands have built up and the server is busy accepting commands rather than responding.

This doesn't seem to be an error / issue / feature request so I'm going to close this. Feel free to reopen if you think it is an error / issue / feature request with the Node.js driver library.
