### ISSUE TITLE
Best Practices / Performance

### ISSUE THREAD

**Issue by kdubious** [NodeRedis/node_redis#1474]
* **Version**: What node_redis and what redis version is the issue happening on?
any?
* **Platform**: What platform / version?
any?
* **Description**: Description of your issue, stack traces from errors and code that reproduces the issue

Given something like an Express application, where the user navigates across various views, loading and editing data... how would you best structure the data access?

And how about in an IoT app, where various sub-processes are reading and writing data?

Is a Singleton pattern a good or bad idea?

Can anyone point to a well written app using this library?

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by kdubious** [comment]
Does anyone know how to use this library properly? Did I ask the question wrong? I’m genuinely looking for feedback around how long to keep the connection open, how to structure access, etc.

**Comment by stockholmux** [comment]
@kdubious There are lots of things written about node_redis around the web - they will have the answers to your questions. Many of these bits of information are not really specific to node.js or this library but general Redis patterns which is also widely written about.

There is no real issue here and this is probably the wrong forum to ask questions like yours (issues are more to report errors, feature requests, etc. not general patterns). That being said, I'm going to go ahead and close the issue.
