### ISSUE TITLE
uncaughtException for read-only database

### ISSUE THREAD

**Issue by bdfy** [NodeRedis/node_redis#238]
I have read-only database. Result uncaughtException:
# !/usr/bin/node

var redis = require('redis'),
client = redis.createClient(), multi

client.on('error', function(error) {
    console.log('error')
})

tasks = []
tasks.push(['set', 'a', 1 ])
tasks.push(['set', 'b', 1 ])

client.multi(this.tasks).exec(function (err, replies) {
   console.log(err)
   tasks = []
   tasks.push(['set', 'a', 1 ])
   client.multi(tasks).exec(function (err, replies) {
   console.log(err)
   })
})

/usr/local/lstat/lstat/node_modules/redis/index.js:468
                throw callback_err;
                      ^
Error: Error: Error: READONLY You can't write against a read only slave.

**Comment by BridgeAR** [comment]
Error handling should have been fixed and this bug should not occur anymore. If I'm wrong, please don't hesitate to reopen the issue!

**Comment by julianfresco** [comment]
@BridgeAR any idea on which version started supporting this master vs slave detection? I would like to know because a third-party module threw this error on me and if I can just update the redis dependency version that would be great

`READONLY You can't write against a read only slave.`

**Comment by BridgeAR** [comment]
@julianfresco the bug fixed here was that an uncaught exception occurred. 

So at the moment there is no master slave detection but each client knows of itself if it is a master or slave (check `client.server_info.role`. This does not work with `no_ready_check` and a server that does not know the info command, as it is returned by the info command) and the default for salves is, that it are read only.

That might be changed on some servers though (even though it is not recommended). In that case you can check this with the already mentioned [config get](http://redis.io/commands/config-get) command.

There is minimal support for slaves as such, as they are only reported ready when the master link status is up but otherwise node_redis still lacks native sentinel and cluster support :disappointed:.
But development is going on and I hope this is supported "soon".

Please have a look at https://github.com/gosquared/redis-clustr. As far as I see it that library has support for what you're looking for. I'm sorry I can't help you any further at the moment.
