### ISSUE TITLE
Unable to connect to google memorystore redis instance with createClient. Erro: Connection Timeout

### ISSUE THREAD

**Issue by logesh2496** [NodeRedis/node_redis#2397]
### Description

Hi, I have setup a google memorystore for redis and got ipaddress and port. When tried to 
`createClient({socket: {host: 'ip', port: '6379'})`, I get connection timedout error. How do I connect with a google memorystore from my computeengine nodejs app?

### Node.js Version

18

### Platform

Ubuntu

**Comment by leibale** [comment]
`redis.createClient(REDISPORT, REDISHOST)` is not a valid configuration, and by default it'll try to connect to `127.0.0.1:6179`. This is the way to configure the client:
```javascript
createClient({
  socket: {
    host: 'host/ip',
    port: 6379
  }
);
```

But this still won't work for you, because [`memorystore` is running in a VPC network](https://cloud.google.com/memorystore#security) (and not connected to "internet"), so in order to connect to it from your local machine [you'll need to create an SSH tunnel](https://cloud.google.com/memorystore/docs/redis/connect-redis-instance)

**Comment by zesameri** [comment]
depending on what platform is hosting your service (cloud run, compute engine, etc.) you can connect it to the redis memorystore. Here's a helpful doc to figure out how : [Memorystore supported environments](https://cloud.google.com/memorystore/docs/redis/supported-environments)

**Comment by leibale** [comment]
@logesh2496 did you solve it?
