### ISSUE TITLE
Which node.js-version is required?

### ISSUE THREAD

**Issue by 4z3** [NodeRedis/node_redis#536]
Ubuntu 12.04 distributes node.js version 0.6 which cannot run node_redis. Maybe add an "engines" field to package.json that specifies the lowest required node.js-version?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
The engine will be added in the next version.
