### ISSUE TITLE
Dead TCP connections

### ISSUE THREAD

**Issue by laino** [NodeRedis/node_redis#540]
__TL;DR__: There should be an option to configure the keepalive property of the underlying socket, with a sane default

When I leave servers running for a longer time (>24hours) redis will at some point stop receiving messages from channels it subscribed to. During that time multiple connects/reconnects (network issues) might have happened.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
