### ISSUE TITLE
try_callback function makes server extremely busy so that all CPU is occupied by node process 

### ISSUE THREAD

**Issue by nickhsine** [NodeRedis/node_redis#543]
Code in index.js

```js
function try_callback(client, callback, reply) {
    try {
        callback(null, reply);
    } catch (err) {
        if (process.domain) {
            process.domain.emit('error', err);
            process.domain.exit();
        } else {
            client.emit("error", err);
        }
    }
}
```

If the callback has a error and the process.domain exists, then my server will be extremely busy and it causes CPU to have almost 100% loading. My server will be hung up there, and it cannot process any new requests.

Can this library avoid accessing the global object(process.domain)? just use redis client emit the error event? And let other programs using the redis client to handle the error event?
Or can anyone help me to avoid that problem?

Thanks in advance.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
