### ISSUE TITLE
MULTI error handling

### ISSUE THREAD

**Issue by guileen** [NodeRedis/node_redis#550]
this callback error  [err, null]

```js
redis.eval('1/0', 0, console.log)
```

But this do not callback error, [null, 'ERR ...']

```js
redis.multi().eval('1/0', 0).exec(console.log)
```

Even this do not callback error,  [null, 'ERR, ...']

```js
redis.multi().eval('1/0', 0, console.log).exec(console.log)
```

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
This is fixed from v.2.0 on.
