### ISSUE TITLE
Best practice for handling drain event

### ISSUE THREAD

**Issue by givan** [NodeRedis/node_redis#554]
Hello,

Is there a recommendation on which RedisClient events should be handled, and how? If the connection is closed, or ended, or error, etc. Will be very useful to know. For example, I want to know how to handle drain event - do i need to subscribe for the drain event, or will be called back with err = Drained.. 

Thank you,
- George

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@givan the low water mark is there to signal from what queue length on you may/should continue sending new commands.
So if you set the low water mark above zero and the stream is buffering, so that there are still some commands not yet processed the drain event is fired anyway as soon as there are a maximum number of commands in the queue left that are lower than the low water mark. So you ignore that some commands could not yet been sent.

**Comment by tuananh** [comment]
@mranney 

```
node_redis: The drain event listener is deprecated and will be removed in v.3.0.0.
If you want to keep on listening to this event please listen to the stream drain event directly.
```

I saw these message today. Could you please update the example?
