### ISSUE TITLE
hiredis as a dependency?

### ISSUE THREAD

**Issue by markreg** [NodeRedis/node_redis#561]
I'm curious, why doesn't redis use hiredis as a dependency?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
The js parser is still very slow at parsing big values and hiredis does support windows. It should be up to the user what parser to use.

@crzidea while creating a new redis client you can pass the "parser" option to specify what parser to use.
