### ISSUE TITLE
changing the redis host and port

### ISSUE THREAD

**Issue by sakari** [NodeRedis/node_redis#565]
Is there currently any nice way to point the existing `RedisClient` to a new redis host? I would need this for crude failover handling :). It would be nice to be able to reuse the logic for resubscribing here like is done for reconnects.

I can get it done by setting the `.port` and `.host` before calling `stream.destroy` after which the reconnect handles connecting to the new host and playing back the subscriptions. This is somewhat crude and feels that I'm tampering with the internals of the library.

If there is no such functionality would you be interested in a pull request for it?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
Reference #302

Changing the `connection_options` is the only way how to achieve this atm. And yes, this is not really recommended. As soon as sentinel is implemented, you'll have the ability to add more hosts though.
