### ISSUE TITLE
Keyspace Notifications

### ISSUE THREAD

**Issue by matejkramny** [NodeRedis/node_redis#573]
Redis supports [keyspace notifications](http://redis.io/topics/notifications), i am wondering whether its possible to use it with this library.

I can't find it in the documentation, and there seem to be no issues/code about it either..

Thanks

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by loretoparisi** [comment]
@jksdua In my case I get the error

```
Notifications not active
ReplyError: ERR unknown command 'config', with args beginning with: 'get' 'notify-keyspace-events' 
    at new Command (/node_modules/redis/lib/command.js:12:22)
    at RedisClient.config (/node_modules/redis/lib/commands.js:58:47)
    at Object.<anonymous> (/redis_keyspace_notif.js:36:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

so apparently it's not possible to activate keyspace notifications here.
