### ISSUE TITLE
reply_to_object function is broken for binary keys

### ISSUE THREAD

**Issue by nick-apperson** [NodeRedis/node_redis#585]
There is currently no way to opt out of the way hgetall works with the node_redis library and if any of the keys have binary, they are incorrectly converted to the charactor 0xFEFF instead. This makes it impossible to fully use HGETALL. See my fork for the fix.

https://github.com/mranney/node_redis/pull/584

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
