### ISSUE TITLE
sentinel support

### ISSUE THREAD

**Issue by henryoswald** [NodeRedis/node_redis#592]
Hi, it would be great if there were support for sentinel. I see there are some wrappers like https://github.com/ortoo/node-redis-sentinel but ideally this module would also cover it.

Thanks for all of your work!

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
