### ISSUE TITLE
mset: parameters as object

### ISSUE THREAD

**Issue by alvassin** [NodeRedis/node_redis#594]
Wondering why it is necessary to make calls like this:
```javascript
redis.mset('key1', 120, 'key2', 2, redis.print);
```
 
when it is much more rational, simple to use this syntax:
```javascript
redis.mset({'key1': 120, "key2": 2}, redis.print);
```

Perhaps this could be a nice feature to implement?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
You can use hmset like that. This is not on the roadmap soon though for other commands.
