### ISSUE TITLE
redis error event

### ISSUE THREAD

**Issue by odirus** [NodeRedis/node_redis#597]
After I pass a function, named A, which will do sth after get redis client, to redis createClient  function,  If the function  A includes some error, redis client will got the error event, How can I avoid it, Thinks。Forgiving my poor English。

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by bgSosh** [comment]
This is still an issue.  Please re-open.

**Comment by blainsmith** [comment]
@brycebaril Since you were on this originally, can you comment on this?

**Comment by brycebaril** [comment]
@blainsmith I believe this *shouldn't* be an issue anymore with https://github.com/NodeRedis/node_redis/commit/08a8eed111b0214b47bc8c3ca9ef7ca77e830b89

@bgSosh maybe elaborate with a repro case?

**Comment by BridgeAR** [comment]
This has been resolved in v.2.0
