### ISSUE TITLE
command hgetall got wrong result sometimes on high concurrency

### ISSUE THREAD

**Issue by ghost** [NodeRedis/node_redis#599]
I have some hash keys like user_c_15401777, the value is:

redis 192.168.5.55:11324[4]> HGETALL user_c_15401777
 1) "cmsgNew"
 2) "0"
 3) "csysmsg"
 4) "81"
 5) "cmessage"
 6) "5274"
 7) "cmessageNew"
 8) "0"
 9) "catmeNew"
10) "0"
11) "cfansNew"
12) "1"
13) "creplyNew"
14) "3"
15) "cfavedNew"
16) "0"
17) "cactive"
18) "8008"
19) "cactiveNew"
20) "1"
21) "csysmsgNew"
22) "0"
23) "csystematNew"
24) "0"
25) "cletterNew"
26) "0"
27) "ctopicMsgNew"
28) "0"
29) "cCartCount"
30) "6"
31) "chatNew"
32) "0"
33) "cCoupon"
34) "0"

We use node_redis to fetch them like:

redisClient.hgetall('user_c_' + userid, function (err, obj) {...}

But there would be wrong results sometimes, about 20 percents, just like:

{ csysmsgNew: '1', csysmsg: '1401185648', cCartCount: '1' }

or

{ csysmsgNew: '2',
  csysmsg: '1356837902',
  cCartCount: '15',
  cCoupon: '0' }

As u see, some keys missed, and the values are not right.

My node_redis version is v0.8.1.

Someone help me, Thanks!

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
