### ISSUE TITLE
Add support for partitioning

### ISSUE THREAD

**Issue by 39dotyt** [NodeRedis/node_redis#600]
Please, add support for redis partitioning.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
Part of #574
