### ISSUE TITLE
.toLowerCase is slow

### ISSUE THREAD

**Issue by dcharbonnier** [NodeRedis/node_redis#605]
According to this http://jsperf.com/regex-vs-tolowercase toLowerCase is slow.
My test consist on doing 1000 multi each containing 100 sadd (real use-case for me).
Replacing toLowerCase with regexp increase performance by 5%, removing possibility of uppercase (using === string with no uppercase alternative) increase performance by 10%. Is there any good reason for allowing different case for functions ? When people use redis most of the time performance is critical.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
Reopened as the issue is still present but going to be fixed soon
