### ISSUE TITLE
Document how to turn callbacks into promises using bluebird

### ISSUE THREAD

**Issue by rayshan** [NodeRedis/node_redis#606]
Many may find this `bluebird` feature useful if they're looking for a redis library that supports promises or manually turning callbacks into promises:

```JavaScript
var Promise = require("bluebird");
Promise.promisifyAll(require("redis"));
var db = redis.createClient...
db.getAsync(key).then()
...
```

More details
https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification

**Comment by komocode** [comment]
Do you have an example on how to use the multi as promises?

**Comment by maxbrieiev** [comment]
For multi only `exec` should return a promise. This lib handles it for you: https://github.com/maxbrieiev/promise-redis

See the very last paragraph.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
Reference #864
