### ISSUE TITLE
replicaset failover

### ISSUE THREAD

**Issue by jefflage** [NodeRedis/node_redis#627]
we're running a replica-set in production and are using redis-sentinel to monitor the replica-set.  we do not allow reads from slaves.  in this configuration, it is possible for there to be a failover/promotion within the replica-set without loosing connection to the master.

when this occurs, there are no errors called-back/emitting by the client until the first time you try to issue a command on the client.  in fact, from that point on, you will end up in the `return_error` function for the client for any call you make.

it seems that the parser/client should handle the 'readonly' error specially and emit an event directly off of the client.  this would make it much cleaner to identify the failover and reconnect.  without this, we would have to wrap the client in some way to then wrap the callback so that we can first check if the error is a readonly error before passing control to the 'real' callback.

do you have any suggestion for a better way to handle this?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@jefflage is this still an issue with node-redis 2.0? There were some major fixes to the error handling.
