### ISSUE TITLE
Is this the correct way of using client.del, as its not working for me!!!

### ISSUE THREAD

**Issue by aamiryu** [NodeRedis/node_redis#630]
var redis = require("redis"),
      universalKey = "abcd_1234";

client = redis.createClient();

client.del(universalKey, function() {
  console.log("Deleted the UNIVERSAL_KEY " + universalKey + "...");
  client.end();
});

I tried everything but it doesn't work at all the way I am coding it. Let me know if I am doing something wrong with the coding part or the syntax.

Many Thanks.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
