### ISSUE TITLE
More Documentation 

### ISSUE THREAD

**Issue by faiq** [NodeRedis/node_redis#636]
Hey! First time redis user here, and I would really appreciate some documentation on what the node functions for redis look like. I know I can see the methods redis has through here http://redis.io/commands# , but  I don't quite understand how to use them in the node client. ie: what params each callback gets if any

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
