### ISSUE TITLE
hgetall on a non-existent key returns null

### ISSUE THREAD

**Issue by jsu1212** [NodeRedis/node_redis#646]
```
var redis = require('redis');
var c = redis.createClient();

c.hgetall('key-does-not-exist', function (err, val) {
    console.log(val);
});
```

This prints null.  I believe this is due to https://github.com/mranney/node_redis/blob/master/index.js#L613.  I think a more useful return value would be {}, which would be in line with what the redis-py client does.

Changing this would have some serious backwards compatibility implications though.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@NodeRedis/contributors do you think this is a neat feature to implement? I do not really care either way.

**Comment by stockholmux** [comment]
I've never really thought about it before but it is a bit weird that `hgetall` returns `null` when the key is not found, but other array commands return arrays if the key doesn't exist. 

Looking at a few different commands:
```
var
  redis   = require('redis'),
  client  = redis.createClient();

client.get('nope:nope:nope',function(err,values){
  console.log('get',err,values); //returns: get null null
});

client.hgetall('nope:nope:nope',function(err,values){
  console.log('hgetall',err,values); //returns: hgetall null null
});

client.hmget('nope:nope:nope','nope','nope',function(err,values){
  console.log('hmget',err,values); //returns: hmget null [ null, null ]
});

client.smembers('nope:nope:nope',function(err,values){
  console.log('smembers',err,values); //returns: smembers null []
});

client.zrange('nope:nope:nope', 0, -1, function(err,values){
  console.log('zrange',err,values); //returns: zrange null []
});

client.lrange('nope:nope:nope', 0, -1, function(err,values){
  console.log('lrange',err,values); //returns: lrange null []
});
```

It's an inconsistency for sure, but from the app perspective it might be easier to check for `null` than to check for `{}`. So, I'm mixed.

**Comment by BridgeAR** [comment]
The default return value is set by redis and not by node_redis. We manipulate the return value from hgetall though, so it returns an object instead of an array and return null if nothing was found. I personally think it's more intuitive to to have null as reply, as you'd otherwise have to check for the object keys, if you want to know if there were any replies.
And that's also what most people seem to [think](67).
