### ISSUE TITLE
ECONNREFUSED on 0.12.1

### ISSUE THREAD

**Issue by LordMonoxide** [NodeRedis/node_redis#648]
I have a local dev server and a remote staging server.  I'm currently writing a very simple node.js app to grab a few pieces of data from mongoDB and store them in Redis.

Setup:
- Redis on both servers
- node.js + node_redis on both servers

Issue:
- From my remote server, I can connect to Redis on both servers via redis-cli (Meaning Redis works?)
- On my local server, I can connect to Redis on my local server via my script (Meaning my script works?)
- On my remove server, I *can not* connect to Redis on either server (even localhost)

It simply says, "Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED"

What could be causing redis-cli to work, but not createClient()?  I have verified that I am using the correct host/port.

See code:
var redislib = require('redis');
var redis = redislib.createClient();

redis.on('error', function(err) { console.log('Error ' + err); });

redis.on('ready', function() {
  console.log('Redis connected.');
});

Am I doing something incorrectly?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
