### ISSUE TITLE
pls no, my pretty output for my test framework is now muttled with uneeded info.

### ISSUE THREAD

**Issue by jjn2009** [NodeRedis/node_redis#655]
https://github.com/mranney/node_redis/blob/master/index.js#L512 
https://github.com/mranney/node_redis/blob/master/index.js#L531

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
