### ISSUE TITLE
Callback when added to a multi queue

### ISSUE THREAD

**Issue by chuntley** [NodeRedis/node_redis#657]
Using the async library I have the following code:

```
          async.each(log_obj, function(log, callback) {
                cache_multi.lpush("log", JSON.stringify(log), function(err, replies) {
                   callback();
                });
            }, function(err) {
                cache_multi.exec(function (err, replies) {
                    callback();
                });
            });
```

Since the multi lpush callback is not fired until the entire queue is executed, looping through an array and adding entries to redis in parallel will not reliably function. Having a way to fire a callback when an item is added to the multi queue should solve this issue.

**Comment by ecasilla** [comment]
+1

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@chuntley wouldn't using the lpush directly without the multi statement be what you want?

**Comment by BridgeAR** [comment]
As multi is there for transactions this is not possible in the way you want it.
