### ISSUE TITLE
"\r\n" appended to the value in the last property of the object from a redisClient.hgetall() call

### ISSUE THREAD

**Issue by atgillette** [NodeRedis/node_redis#660]
When I save a value to a hash using: redisClient.hmset(phoneId, "someId", "abb0f933b4b31de51505a11a381f86ad");
I get the follow back from redisClient.hgetall(): {"myId":"GcDCHED0rcis9o48AAAB","someId":"abb0f933b4b31de51505a11a381f86ad\r\n"}

Notice the "\r\n" in "someId".

Is this a bug in node_redis or am I doing something wrong?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
