### ISSUE TITLE
No return Buffer if connect via unix.socket

### ISSUE THREAD

**Issue by aleksraiden** [NodeRedis/node_redis#672]
If use options return_buffers: true, we cant fetch Buffer at callback, only string, while we connecting to Redis instance via Unix-socket (e.g. /var/run/redis.sock). If reconnect using  TCP, all ok.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
Reopening this as there are still more errors with `return_buffers`

Reference #818

**Comment by BridgeAR** [comment]
The buffer issues should have been fixed by 55e4a9b847b15f535d1538241c98554de7c14af8. @aleksraiden please check if your issue persists and reopen if.
