### ISSUE TITLE
Getting Server "unknown reply type error"

### ISSUE THREAD

**Issue by jorgeolivero** [NodeRedis/node_redis#674]
My team and I are getting this error on what we believe is a set of Redis connections that are being using for PUB/SUB subscriptions. 
   
    ErrorError: subscriptions are active but got unknown reply type u9 bscribe at RedisClient.return_reply 

[Tracked this down to line #691 in index.js](https://github.com/mranney/node_redis/blob/master/index.js#L691-L715)

The users are subscribing on channels by user_id. Mostly just confused as to what is happening here because the reply type in these errors is constantly changing to random strings like the one above  ("u9 bscribe"). Here are list of others in stack traces that we've been seeing.

- $ubscribe
- subscibe
- s9bscribe
- un bscribe
- dispatch:yGC99P-dF7L2ETicyS-x 
- unsubscri

In addition to that one, we've been receiving this error that I have not been able to get more context on: 
     
    ErrorError: Redis reply parser error: Error: Protocol error, got "h" as reply type byte at HiredisReplyParser.execute 

Thanks in advance for the help

**Comment by matthewhafner** [comment]
Hello All,

Has anyone found a cause/solution for this issue? I am having the same problems as the initial post.

Nodejs v0.10.31
redis server: 2.8.12
node_redis: v0.7.3 

Thank you very much.

**Comment by Hackuracy** [comment]
hi,
I had the same problem due to haproxy.
balancing with HTTP can't work

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@jamiter your issue is going to be fixed by #818. To prevent this from happening right now please don't return buffers
@janajri the second error you got seems to be a out of memory issue that can't be handled by hiredis yet

If any of the issues besides the mentioned ones persist, please mention that so I'll reopen this ticket.

**Comment by cccheck** [comment]
We have the original issue `Protocol error, got "i" as reply type byte` using `hiredis `for node. It occurs occasianally under sustained heavy load.

Redis 3.0.7
redis 2.6.0.1 (via npm)
hiredis 0.4.1 (via npm)
Node 4.2.4
