### ISSUE TITLE
Obtain a ReadStream of the Redis database

### ISSUE THREAD

**Issue by hellboy81** [NodeRedis/node_redis#683]
In `LevelUP` it is very simple to iterate all keys and values using [readable stream][1].

How can I do get all records (**both** *keys* and *values*) from Redis store (may be as `ReadStream`)?

May be should I use [SCAN][2] command?

  [1]: http://git.io/0XKz1Q
  [2]: http://redis.io/commands/scan

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
