### ISSUE TITLE
Code straight out of README fails to run

### ISSUE THREAD

**Issue by edufelipe** [NodeRedis/node_redis#690]
From the README in `node_redis` I got the following excerpt:

> All functions take either an args Array plus optional callback Function or a variable number of individual arguments followed by an optional callback. 

But turns out that is not what's happening. If I try to run the following code (straight out of the README examples):

```
var redis = require("redis"),
    client = redis.createClient();

client.on("error", function (err) {
    console.log("Error " + err);
});

client.set(["some key", "some val"]);

setTimeout(function () {}, 100000);
```

I get this nice exception (which also interrupts my execution despite setting `client.on("error", ...`):

```
node_redis: no callback to send error: ERR wrong number of arguments for 'set' command

node_modules/redis/index.js:582
            throw err;
                  ^
Error: ERR wrong number of arguments for 'set' command
    at HiredisReplyParser.execute (node_modules/redis/lib/parser/hiredis.js:30:33)
    at RedisClient.on_data (node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

If I instead add a callback to that function it works perfectly:

```
client.set(["some key", "some val"], redis.print);
```
```
Reply: OK
```

The issue so is two fold: first callback is not optional as mentioned on the docs, second the program is ending when it shouldn't.

I'm using Node v0.10.33, node_redis 0.12.1 and hiredis 0.1.17.

**Comment by Guuz** [comment]
It's troubling that no one seems to be looking at this. This project is still active, right?!

**Comment by asilvas** [comment]
+1

**Comment by brycebaril** [comment]
@Guuz yes still active, but we're busy people. I'm sure you understand.

Yes, this is a bug in argument parsing -- but it's also not the highest priority because it's an unusual one to come across. The README being misleading is unfortunate, happy to entertain any pull requests to fix either the argument parsing or just fixing the README.

**Comment by Guuz** [comment]
Sorry @brycebaril, i might have come of a bit hard there. I ran into a bug and was browsing through the issues and saw a lot of pretty serious things that did not even get a comment yet. I understand you are busy and I hope someone has the time to help the project out. There really are a lot of open issues.

**Comment by brycebaril** [comment]
Yeah, fairly overwhelmed between this and work and everything else. I have been actively working on a fairly large-scale refactor of the library to fix many issues at once but it is slow going.

Always welcoming any maintenance help :wink:

**Comment by poliveira89** [comment]
I have some problems with this module, as well.(I didn't know if I should create a new issue or reuse this one, since my problem is similar).

I'm having trouble executing code based on README or any docs. I have created a new file `sample-redis.js`:

````javascript
var redis = require('redis');
var client = redis.createClient();
console.log('Redis connection initiated.');
client.on("error", function (err) {
    console.error(err);
});
var res = client.select(2);
console.log('Redis -> SELECT 2: '+res);
res = client.set('WLAN', 'Wide Local Area Network', redis.print);
console.log(res);
console.log('--');
res = client.get('WLAN', function(err, reply) {
    if(err) { console.error(err); }
    console.log(reply);
});
console.log(res);
client.end();
console.log('Redis connection terminated.');
console.log();
````

Executing this on a terminal, outputs this:
````bash
vagrant@vagrant-ubuntu-trusty-64:~/nodejs$ node sample-redis.js
Redis connection initiated.
Redis -> SELECT 2: undefined
false
--
false
Redis connection terminated.
````
If you did not noticed, the `redis.print`did not executed and the methods on `client` returned `false` followed by the unavailability of the value for the key `WLAN`.

But the strange part is, if I execute `node` and open a node console, this code works:
````bash
vagrant@vagrant-ubuntu-trusty-64:~/nodejs$ node
> var redis = require('redis');
undefined
> var client = redis.createClient();
undefined
> client.on('error', function(err) { console.log(err); });
{ stream:

    ...

    }
> client.select(2);
undefined
> client.set('WLAN', 'Wide Local Area Network', redis.print);
true
> Reply: OK

undefined
> client.get('WLAN', function(err, reply) { console.log(reply); });
true
> Wide Local Area Network
````

In the console, everything is different: I received an error from `on('error', ...)` that I have minified by size purposes, and I was able to `SET` and  `GET` and receives the proper replies from it.

I'm using Vagrant with ubuntu/trusty64, I have installed `node`, `nodejs-legacy` and `npm` packages.
````bash
vagrant@vagrant-ubuntu-trusty-64:~/nodejs$ node --version; npm --version
v0.10.25
1.3.10
````
On nodejs modules, I have: redis (0.12.1) and hiredis (0.2.0)

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@edufelipe @Guuz @asilvas that issue is resolved with v.2.0 and I highly recommend updating to that version as it fixed most issues people were running into.

@poliveira89 you do not wait until the async operation is done, so you can't expect any reply.
