### ISSUE TITLE
Channel names with spaces not properly resubscribed

### ISSUE THREAD

**Issue by pbihler** [NodeRedis/node_redis#691]
If you use channel names with spaces, `client.subscribe('foo bar')` works fine, but after a reconnection, only `foo` is resubscribed on redis.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
