### ISSUE TITLE
Set command automatically sends expire as well

### ISSUE THREAD

**Issue by yellowandy** [NodeRedis/node_redis#703]
I'm currently setting a key/value with the basic set command (not expire) and noticed something weird in the logs. I saw the following while telneted into redis with the MONITOR command:

+1420445962.505686 [0 10.0.1.220:58459] "set" test@abc.com_initialSync" "true"
+1420445962.505698 [0 10.0.1.220:58459] "expire" "test@abc.com_initialSync" "100"

I never issued the expire command and I'm not sure where it could be coming from. The TTL in fact does get set and as a result I loose all my keys. Any ideas if the node package could be causing this?

**Comment by brycebaril** [comment]
I wouldn't expect this library alone to be causing this -- are you using some other library that abstracts communication to Redis?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
