### ISSUE TITLE
Error: Trying to open unclosed connection

### ISSUE THREAD

**Issue by gagle** [NodeRedis/node_redis#708]
Scenario:

- Start Redis server
- Create redis client (retry_max_delay: 1000ms)
- Kill the Redis server
- Reconnection starts every second
- Start Redis server
- Booooom `Trying to open unclosed connection`

**Comment by brycebaril** [comment]
Interesting, thanks for the report -- there are a family of issues related to reconnection right now.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@gagle Could you check if this is still an issue with v.2.0? I guess that is already fixed but it would be great to be sure about it.
