### ISSUE TITLE
Group [member, score] when using WITHSCORES

### ISSUE THREAD

**Issue by nacholibre** [NodeRedis/node_redis#712]
When trying to get members of sorted set with scores, the client returns them as `[member1, score1, member2, score2]` and making `[ [member1, score1], [member2, score2] ]` is almost always necessary. I think the client should do that for you. What do you think?

I know this will break the API and probably slow down the client, but this doesn't make it bad idea. In order to use the scores or the members they should be paired in the array.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@nacholibre could you write an example for me to look at?

**Comment by nacholibre** [comment]
var args = [ 'myzset', 0, 99, 'WITHSCORES';
    client.zrevrange(args, function (err, response) {
        if (err) throw err;
        console.log(response);
    });

The returned response is in format:
`[member1, score1, member2, score2]` and I think it's better to return `[[member1, score1], [member2, score2]]`

**Comment by BridgeAR** [comment]
Duplicate of #97 (it would be returned as an object instead of a two dimensional array).

If it would not be a BC I'd add it in soon, but that way it'll have to wait until 3.0.
