### ISSUE TITLE
SCRIPT LOAD with invalid lua script does not receive error

### ISSUE THREAD

**Issue by enobufs** [NodeRedis/node_redis#715]
I am loading lua script like below and noticed that the callback does not return error (in 1st arg) when an invalid lua script is passed.

When such compile error occurs, shouldn't it fail with the first arg of the callback (`err') being an Error object?

```js
$ node
> var c = require('redis').createClient()
undefined
> c.multi([['script', 'load', 'INVALID LUA']]).exec(function () { console.log('args=', arguments); });
true
> args= { '0': null,
  '1': [ 'ERR Error compiling script (new function): user_script:1: \'=\' expected near \'LUA\' ' ] }
```

I am using redis (client) v0.12.1. The v0.10.0 and v0.11.0 behave the same way... fyi.

**Comment by dionjwa** [comment]
+1

**Comment by BridgeAR** [comment]
That is intended behavior. The error did not occur while queuing the command but while executing it. Since the transaction is not rolled back the error is returned in the result handler. Otherwise there could be errors and results being returned at the same time. For further infos check [transactions](http://redis.io/topics/transactions).
