### ISSUE TITLE
Psubscribe

### ISSUE THREAD

**Issue by StephaneC** [NodeRedis/node_redis#753]
Looks like there is trouble using psubscribe in last version (0.12.1).
when I use this, i receive message
redisSub.subscribe('/checktoken');
When i use this, nothing happen:
redisSub.psubscribe('*');

Nothing change except that in my code.

(Project here: https://github.com/StephaneC/SocketIoToBus)

**Comment by bcoe** [comment]
Hey @StephaneC I think the problem is that you should be calling:

`client.on('pmessage')` rather than `client.on('message')`, if you're using `psubscribe`.

I've added a unit test for your specific use-case, 

https://github.com/NodeRedis/node_redis/pull/796

let me know if you continue to run into problems and we can reopen this ticket.

**Comment by BridgeAR** [comment]
@bcoe we might consider consolidating the event handler, don't you think so?
