### ISSUE TITLE
Eval failing on Redis failover

### ISSUE THREAD

**Issue by knguyen2525** [NodeRedis/node_redis#769]
Hello,

I am currently using redis-sentinel (https://www.npmjs.com/package/redis-sentinel) to cluster multiple redis-servers together; their Redis client is based on node_redis. 

I am using the eval command to run lua scripts on the current master of my cluster. The problem is that when the redis master fails and failover occurs, the eval command isn't buffering and being replayed when the next master goes up.  

Should this be the case when a failover occurs? I assume a failover would be similar to a single redis-server restart so should commands during this restart time be behaving similarly?

Thanks

**Comment by raydog** [comment]
This seems like it is actually expected behavior. If there is a bug here, it would probably be in the other project. I glanced at node-redis-sentinel's code, and AFAICT, the only thing that they do is open a new connection to the newly selected master, which is reasonable. It would be nice if they transferred UNSENT commands to the new client, just so long as they don't transfer the PENDING commands as well, as there are many cases where a command might have succeeded and replicated, but we didn't hear about it. That would cause a query to be executed twice...

Also note that redis doesn't have guarantees that a single-server reboot won't cause commands to be lost.
