### ISSUE TITLE
[P0] temporary feature freeze and spring cleaning

### ISSUE THREAD

**Issue by bcoe** [NodeRedis/node_redis#881]
We've done a lot of amazing work on node_redis recently. I'm particularly amazed by all the hard work that @BridgeAR has put in! I think we all owe him a round of applause :clap: :clap: :clap:

Looking at the current state of our Windows tests, and #875 which appears to be a rather nasty regression, I think we should take a temporary break from landing any _new feature tickets_ and do a bit of spring cleaning:

1. let's get our Windows tests in tip top shape, so that they don't create signal-noise for us when running pull requests on CI:
 * https://github.com/NodeRedis/node_redis/issues/880
2. let's reproduce #875, and get the issue patched.

Going forward I'd like to better balance new features (performance tweaks, refactors) with stability fixes (patches to known bugs, test-suite improvements). An approach that I've used in the past is:

1. push new candidate releases of your library to an alternate tag on npm, e.g., `next`.
2. identify key users of the library, e.g., @zaggino, @torra, @bcoe, and request that they try out the candidate releases before we promote them. _This will put us in a position to find issues like #875 at the exact time that they're introduced, making the forensics a bit easier._
3. I think we can move a bit faster if we move a bit slower with our releases -- specifically as outlined above I'd like to get a better beta testing strategy in place.

It's exciting to watch the speed of development on this project!

CC: @brycebaril @BridgeAR @mranney @erinspice @blainsmith, @torra, @zaggino

**Comment by BridgeAR** [comment]
Thanks for the praise. I'll do my best to earn it.

I wrote about #875 in #880. I personally also think that stability should always be first priority. Then (depending on the use case) speed and or features.

But I disagree that we should stop landing new features right now. Every feature that I add is fully tested and I actually add new tests and increase the coverage constantly. I also do not think that #875 is as critical as you think it is, as I'm sure we'll fix it very soon (version 2 is out for just a bit above two weeks now). There is one issue though that I'm thinking a lot about: earlier we did not prevent users from adding commands to a closed client. Those commands were never executed but as I tried to update a couple of depending libraries I saw that denying commands after the user closed the connection often results in chaos in those libraries. So I'm thinking of reintroducing the faulty behavior and adding the proper one behind a flag so that those libraries can at least get all the other fixes right now and fix there behavior later on. 

Your suggestions about release candidates is something I thought about. But we already have a couple of people testing our releases all the time. If you have a look at the people cloning the library you'll realize that it's always happening if we pushed new fixes / features. And there are not a lot of people who constantly test things otherwise.
