### ISSUE TITLE
Using .exec() mutliple times on the same multi object, does not behave as README claims

### ISSUE THREAD

**Issue by tomsun** [NodeRedis/node_redis#923]
The README currently claims that re-running .exec() on a multi object that increments a key, is expected to increment the key once per .exec()
https://github.com/NodeRedis/node_redis/commit/85b0f6009d5a44d2186cfa0b4465ba91d295612a#diff-04c6e90faac2675aa89e2176d2eec7d8R269
(I'm deducing that claim from the example output: `// 101, 2`,  `// 102, 3`)

When trying to reproduce, my first exec() produces `[ 101, 2 ]` and the second produces `[]` (unless I add more operations to the multi object before running .exec() again).

Observed with v2.3.0

--- 

I don't mind the observed behavior; just want to make sure `node_redis` considers this the expected behavior - and README suggests otherwise.

**Comment by BridgeAR** [comment]
Thanks for pointing this out! I was not aware, that this was supported. I removed the comment in the ready. Otherwise there would have been some downsides to re-enable this behavior and it should likely be a rare use case. If anyone feels otherwise, please feel free to comment to support re-enabling this.
