### ISSUE TITLE
BRPOP does not trigger callback on LPUSH

### ISSUE THREAD

**Issue by airportyh** [NodeRedis/node_redis#936]
I am coming across this bug when trying to use https://www.npmjs.com/package/simple-redis-queue. I narrowed it down to this:

```
var redis = require('redis');
var client = redis.createClient();

client.brpop('list', 0, function(err, replies) {
  console.log('ITEM', err, replies);
});

client.lpush('list', 1);
```

The callback to `brpop` will not get called if list initially contains zero items. If on the other hand, the list contains at least one item before the `brpop` call, then the callback registers.

```
var redis = require('redis');
var client = redis.createClient();

client.lpush('list', 1);
client.brpop('list', 0, function(err, replies) {
  console.log('ITEM', err, replies);
});
```

Is this a bug or a feature?

**Comment by BridgeAR** [comment]
@airportyh the mentioned library uses node_redis ~0.8.2 and was not maintained since three years. Therefor it should likely not be used at all.

The reason why your first example does not work is, that you use the same client to push new items and to pop them. So brpop blocks the connection and waits that another client pushes something. But instead, you try to push something with a blocked client and that command will never be handled.

**Comment by airportyh** [comment]
@BridgeAR thank you very much for the explanation!
