### ISSUE TITLE
Redis get or set inside express route

### ISSUE THREAD

**Issue by AliUz** [NodeRedis/node_redis#971]
I am having some severe memory leak issues, I have two endpoints, one does a set and the other one does a get from redis. Each request coming from the client goes to either one route, and there a lot of requests coming in. Would having a get or set inside the express route function cause a memory leak? If it does, is there a way around this?

Example code: 
```
            function (req, res) {
                var id = req.get('id');
                redisClientMaster.get(id, function (err, reply) {
                    // do something with id
                    res.send({code: 100, message: 'SUCCESS', data: returnObject});
                });
            }
```

**Comment by stockholmux** [comment]
Generally speaking, no. Nothing about doing a Redis operation inside a route should cause problems (I do it all the time). Looking at your code, I'm assuming you're handling errors somehow but just haven't shown it, otherwise it looks fairly normal.

I would guess that your memory leak is in your app logic somewhere. I'm going to go ahead and close this as we can't really re-create any conditions with your example code. If you can show us a reproducible example that is causing a memory leak, we'll be glad to take a look.

**Comment by BridgeAR** [comment]
@AliUz do you have more details? How did you detect the leak and do you have a heap dump that indicates a redis leak?
