### ISSUE TITLE
Callback not being called

### ISSUE THREAD

**Issue by emilsedgh** [NodeRedis/node_redis#984]
Hi.
We have a very curious case in which our callback to hgetall is not being called. 
This happens randomly so we don't have a reliable way of reproducing it.

This issue happens on both JavascriptParser and Hiredis.

In order to track it better, we put some logs and got interesting results.

On hiredis.js, line 32, I added this:

```javascript
console.log('HiRedis reply', JSON.stringify(data), typeof reply, reply);
```

This is supposed to show the buffer we got from redis and the reply from this.parseData() on hiredis.

The interesting part seems to be this:

![background24](https://cloud.githubusercontent.com/assets/120439/13236937/22fa0a36-d9c8-11e5-84dd-4ffff5ce6c2c.png)

As you can see, there is some data to be parsed (lets call this Buffer A). But its parsed as an empty array.

However, a similar buffer (in the same environment) gets parsed like the following:
![background24](https://cloud.githubusercontent.com/assets/120439/13236980/655f0188-d9c8-11e5-9e7f-bad70ea4a0a2.png)

So I thought maybe Buffer A has corrupted data. Here is the Buffer A for easy copy/pasting.
```javascript
   {"type":"Buffer","data":[42,56,13,10,36,57,13,10,99,108,105,101,110,116,95,105,100,13,10,36,51,54,13,10,98,102,48,100,97,52,55,101,45,55,50,50,54,45,49,49,101,52,45,57,48,53,98,45,48,48,50,52,100,55,49,98,49,48,102,99,13,10,36,55,13,10,117,115,101,114,95,105,100,13,10,36,51,54,13,10,101,99,101,49,102,50,54,97,45,100,50,54,102,45,49,49,101,53,45,56,51,99,52,45,48,50,52,50,97,99,49,49,48,48,48,53,13,10,36,52,13,10,116,121,112,101,13,10,36,55,13,10,114,101,102,114,101,115,104,13,10,36,53,13,10,116,111,107,101,110,13,10,36,52,56,13,10,90,68,107,52,78,71,81,119,90,84,65,116,90,68,108,105,89,105,48,120,77,87,85,49,76,84,108,107,78,84,77,116,78,106,85,120,89,87,90,108,89,50,74,109,78,71,73,49,13,10]}
```

So I wrote this snippet to try it out and see whats wrong with it:

```javascript
var Parser = require('./index.js');
function returnReply() {
  console.log('REPLY', arguments)
}
function returnError() {
  console.log('ERR', arguments)
}

var p = new Parser({returnReply,returnError});

[
  '{"type":"Buffer","data":[42,56,13,10,36,57,13,10,99,108,105,101,110,116,95,105,100,13,10,36,51,54,13,10,98,102,48,100,97,52,55,101,45,55,50,50,54,45,49,49,101,52,45,57,48,53,98,45,48,48,50,52,100,55,49,98,49,48,102,99,13,10,36,55,13,10,117,115,101,114,95,105,100,13,10,36,51,54,13,10,101,99,101,49,102,50,54,97,45,100,50,54,102,45,49,49,101,53,45,56,51,99,52,45,48,50,52,50,97,99,49,49,48,48,48,53,13,10,36,52,13,10,116,121,112,101,13,10,36,55,13,10,114,101,102,114,101,115,104,13,10,36,53,13,10,116,111,107,101,110,13,10,36,52,56,13,10,90,68,107,52,78,71,81,119,90,84,65,116,90,68,108,105,89,105,48,120,77,87,85,49,76,84,108,107,78,84,77,116,78,106,85,120,89,87,90,108,89,50,74,109,78,71,73,49,13,10]}'
]
.map(json => {
  var b = new Buffer(JSON.parse(json).data);
  p.execute(b)
})
```

And here is the output I got:
![background24](https://cloud.githubusercontent.com/assets/120439/13237073/1945bb6a-d9c9-11e5-85de-165e299e428a.png)

And to my surprise, it got parsed just fine.

Reading JavascriptParser's code, it seems that it depends a lot of the current state of variables like `this.chunkSize`, `this.offset`, `this.offsetCache`.

Is it possible that they have wrong stored values inside them, and their corrupted state causes failure to parse the buffer properly?

(Although as I said, the issue happens randomly on both parsers)

**Comment by BridgeAR** [comment]
As this is happening with the hiredis parser too, this is highly unlikely an issue with the parser. What node_redis version do you use?

Your output of the allegedly second buffer is actually the output of the first one as the parser does not work with "number of input buffers === number of responses". It receives buffer chunks of arbitrary data written in RESP that do not correspond to a single response but to arbitrary many depending on the provided data and a chunk may result in no response (the chunk did not contain all needed data) or in a couple (multiple responses sent in a single chunk) including incomplete responses.

Please check the input, since I have the feeling that you actually saved `JSON.stringify([])` at some point. Please also activate the debug mode to check what is happening (you can use the `NODE_DEBUG=redis` environment variable).

If you could show me some code that you use to execute your calls I might be able to help you more.

**Comment by emilsedgh** [comment]
Used version was `2.4.2`.
I enabled debugging on the module earlier and got `netread` outputs.
But I added my own logs so I can do a JSON.stringify() on the buffer.

I will reproduce the issue and get back to you with logs.

One more thing.

As the subject implies, the bug we're experiencing is that our callback is not being called on random occasions.

But it seems that once new redis commands are issued, the callback we were waiting for gets called as well.

Like this:

* hgetall
* (No callback being called for several seconds)
* another activity like another hgetall
* callback called for both hgetall's with proper values

So as you said I might have been looking in totally wrong places.

Our code was initially like this:

```javascript
Token.get = function (token, cb) {
  redisClient.hgetall(token, cb);
};
```
So in order to see whats wrong, we changed it to this:

```javascript
Token.get = function (token, cb) {
  console.log('Token.get called', token);
  redisClient.hgetall(token, (err, res) => {
    console.log('Token fetched from redis', token);
    cb(err, res);
  });
};
```

Also I wanted to apologize for such a vague and unspecific bug report.

**Comment by BridgeAR** [comment]
As far as I understand you the callback is called but not when you think it should be called.

This sounds very much like an issue with the network connection and I guess the network connection dropped and the command landed in the offline_queue instead of being fired directly. So as soon as the connection is reestablished all commands in the offline_queue fire and you'll receive the result shortly afterwards.

In that case you should get error and reconnect events emitted.

**Comment by emilsedgh** [comment]
I actually had some logs on offline_queue and command_queue and it seemed that offline_queue was empty. I will add more logs and come back to you with more logs.

Again, sorry for such a vague bug report. I'm trying to provide as much as details as I can.

**Comment by emilsedgh** [comment]
Indeed it seems that no data comes through network. This seems fixed by updating to a newer redis for us.
This seems like a totally invalid bug report so I'm closing it.

Thank you for the great library and awesome maintenance.

**Comment by BridgeAR** [comment]
Thanks for the report and good to know that it helped in the end.
