### ISSUE TITLE
Getting redisReaderFeed error

### ISSUE THREAD

**Issue by sharathm** [NodeRedis/node_redis#991]
Hi All,

We are currently using `node-redis` to connect to a ElastiCache instance.
Everything runs fine for a while.. but, we see the following error in our nodejs application..

```
nodejs: ../src/reader.cc:191: static Nan::NAN_METHOD_RETURN_TYPE
hiredis::Reader::Feed(Nan::NAN_METHOD_ARGS_TYPE): 
Assertion `redisReaderFeed(r->reader, data, length) == 0' failed.
```

After this, our application crashes and needs to be restarted. 

At first we thought it might be a availability issue since we were running a single instance inside a cluster. 
Then referring to comments in #674 ... we thought it might be memory issue and so we upgraded our EC2 instances. 

We do experience some peak in our load but that is ~4000 keys being written to ElastiCache. 
ElastiCache does not show any signs of down time.

Can anyone shed some light as to what could be going on here?

We are running..

`node 4.3.1`
`node-redis 2.4.2`

**Comment by BridgeAR** [comment]
This issue is happening in the [hiredis-node](https://github.com/redis/hiredis-node) wrapper or in [hiredis](https://github.com/redis/hiredis) itself. Please open a ticket there. There is nothing I can help you with right now but to recommend to switch to the javascript-parser and check if this works out for you. There should not be any performance difference that you can measure if you do not rely on very big SUNION/SINTER/LRANGE/ZRANGE commands.

**Comment by BridgeAR** [comment]
Closing this out of the already mentioned reason. If you have any further detail, I would be interested in the outcome though.
