### ISSUE TITLE
Integers larger than `MAX_SAFE_INTEGER` should be returned as a String

### ISSUE THREAD

**Issue by Mattijah** [NodeRedis/node_redis#994]
JavaScript uses a 64-bit floating point representation (https://en.wikipedia.org/wiki/IEEE_floating_point)  which means that numbers larger than `Number.MAX_SAFE_INTEGER` (2^53) can not be represented precisely.

**Example:**
```javascript
var keyName = "foo",
    value = Number.MAX_SAFE_INTEGER;

client.set(keyName, value, function(err, reply) {
    setInterval(function() {
        client.incrby(keyName, 1, function(err, reply) {
            console.log(reply);
        });
    }, 1000);
});
```

**Result:**
```
9007199254740992
9007199254740992
9007199254740994
9007199254740996
9007199254740996
9007199254740996
9007199254740998
9007199254741000
9007199254741000
9007199254741000
9007199254741002
9007199254741004
9007199254741004
...
```

As you can see the result contains duplicated (incorrect) values. To fix this issue the parser should check whether the value (Number) that is being parsed is larger than `MAX_SAFE_INTEGER` if so then a `String` should be returned.

**Comment by BridgeAR** [comment]
The issue is, that the hiredis parser does not return numbers as buffers or strings, so right now, there's no possibility to do this. I could implement this in the javascript parser, but I want to stay coherent.

@badboy we spoke about this issue before. Shall I open a issue in hiredis-node to return big numbers as string or buffer? 

Reference #339 (likely more)

**Comment by badboy** [comment]
I'd happily integrate it into hiredis-node. Just didn't find the time to do it myself.

**Comment by luin** [comment]
I opened an issue on hiredis-node last year: https://github.com/redis/hiredis-node/issues/82. Love to help but I don't know much about C++. :cry:

**Comment by BridgeAR** [comment]
Ok, I tried to implement this in hiredis-node today but my C++ knowledge is also very low and I have to read some things up before I get to that again. 
So I decided to implement it in the JS Parser and released v.1.2.0 including the new option. In case someone wants use the hiredis parser and wants big numbers it gracefully chooses the JS parser instead of hiredis.
